//
// Created by brymher on 16/01/25.
//

#ifndef CONSTANTS_H
#define CONSTANTS_H

constexpr uint32_t MAX_FRAMES_IN_FLIGHT =  2;

// Device errors start from 1000
#define NO_DEVICE_SELECTED_EXCEPTION 200
#define FAILED_TO_SELECT_PHYSICAL_DEVICE 201
#define MISSING_QUEUE_FAMILIES_FOR_DEVICE 202
// logical device errors start from
#define LOGICAL_DEVICE_CREATION_FAILED 300
// Surface errors start from 100
#define GLFW_WINDOW_SURFACE_CREATION_FAILED 100
#define NO_VALID_SURFACE_FORMAT_FOUND 101
#define FAILED_TO_CREATE_SWAP_CHAIN 102
#define FAILED_TO_CREATE_SWAP_CHAIN_IMAGE_VIEWS 103
#define FAILED_TO_CREATE_RENDER_PASS 125
#define VULKAN_FAILED_TO_END_COMMAND_BUFFER 130
#endif //CONSTANTS_H
